/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export const ErrorCodes = {
  IncorrectTokenIndex: BigInt("0"),
  NFTNotFound: BigInt("1"),
  NFTNotPartOfCollection: BigInt("2"),
  MaxSupplyReached: BigInt("3"),
  MintEnded: BigInt("4"),
  MintNotStarted: BigInt("5"),
  LimitedMintPerAddress: BigInt("6"),
  InvalidCaller: BigInt("7"),
  NotBurnable: BigInt("8"),
  NotEnoughAlph: BigInt("9"),
  AlreadySet: BigInt("10"),
  InvalidPassword: BigInt("11"),
};
