/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as PoapNFTSerieV2ContractJson } from "../V2/series/PoapNFTSerieV2.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Trait, AllStructs } from "./types";

// Custom types for the contract
export namespace PoapNFTSerieV2Types {
  export type Fields = {
    collectionId: HexString;
    nftIndex: bigint;
    eventImage: HexString;
    eventName: HexString;
    description: HexString;
    organizer: HexString;
    location: HexString;
    eventStartAt: bigint;
    eventEndAt: bigint;
    isPublic: boolean;
    minter: Address;
    isBurnable: boolean;
    lockedUntil: bigint;
    hasParticipated: boolean;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getTokenUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getCollectionIndex: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[HexString, bigint]>;
    };
    getNFTIndex: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDescription: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getImage: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getTraits: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<
        [Trait, Trait, Trait, Trait, Trait, Trait, Trait, Trait, Trait]
      >;
    };
    getTraitCount: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTraitAtIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<Trait>;
    };
    getHasParticipated: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<boolean>;
    };
    getMinter: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    burn: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    setParticipated: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    lock: {
      params: CallContractParams<{
        recipient: Address;
        lockedPresenceUntil: bigint;
      }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getTokenUri: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getCollectionIndex: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getNFTIndex: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getDescription: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getImage: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTraits: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTraitCount: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTraitAtIndex: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getHasParticipated: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getMinter: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    burn: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    setParticipated: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    lock: {
      params: SignExecuteContractMethodParams<{
        recipient: Address;
        lockedPresenceUntil: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  PoapNFTSerieV2Instance,
  PoapNFTSerieV2Types.Fields
> {
  encodeFields(fields: PoapNFTSerieV2Types.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): PoapNFTSerieV2Instance {
    return new PoapNFTSerieV2Instance(address);
  }

  tests = {
    getTokenUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapNFTSerieV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getTokenUri", params, getContractByCodeHash);
    },
    getCollectionIndex: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapNFTSerieV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<[HexString, bigint]>> => {
      return testMethod(
        this,
        "getCollectionIndex",
        params,
        getContractByCodeHash
      );
    },
    getNFTIndex: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapNFTSerieV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getNFTIndex", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapNFTSerieV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getDescription: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapNFTSerieV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getDescription", params, getContractByCodeHash);
    },
    getImage: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapNFTSerieV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getImage", params, getContractByCodeHash);
    },
    getTraits: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapNFTSerieV2Types.Fields, never>,
        "args"
      >
    ): Promise<
      TestContractResultWithoutMaps<
        [Trait, Trait, Trait, Trait, Trait, Trait, Trait, Trait, Trait]
      >
    > => {
      return testMethod(this, "getTraits", params, getContractByCodeHash);
    },
    getTraitCount: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapNFTSerieV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTraitCount", params, getContractByCodeHash);
    },
    getTraitAtIndex: async (
      params: TestContractParamsWithoutMaps<
        PoapNFTSerieV2Types.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<Trait>> => {
      return testMethod(this, "getTraitAtIndex", params, getContractByCodeHash);
    },
    getHasParticipated: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapNFTSerieV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(
        this,
        "getHasParticipated",
        params,
        getContractByCodeHash
      );
    },
    getMinter: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapNFTSerieV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "getMinter", params, getContractByCodeHash);
    },
    burn: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapNFTSerieV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "burn", params, getContractByCodeHash);
    },
    setParticipated: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapNFTSerieV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setParticipated", params, getContractByCodeHash);
    },
    lock: async (
      params: TestContractParamsWithoutMaps<
        PoapNFTSerieV2Types.Fields,
        { recipient: Address; lockedPresenceUntil: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "lock", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: PoapNFTSerieV2Types.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const PoapNFTSerieV2 = new Factory(
  Contract.fromJson(
    PoapNFTSerieV2ContractJson,
    "",
    "5eafdf51e14a05eb56f826a111b5cbd4e4cf3ffec834b8c5d3ce813dd7b9b9f0",
    AllStructs
  )
);
registerContract(PoapNFTSerieV2);

// Use this class to interact with the blockchain
export class PoapNFTSerieV2Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<PoapNFTSerieV2Types.State> {
    return fetchContractState(PoapNFTSerieV2, this);
  }

  view = {
    getTokenUri: async (
      params?: PoapNFTSerieV2Types.CallMethodParams<"getTokenUri">
    ): Promise<PoapNFTSerieV2Types.CallMethodResult<"getTokenUri">> => {
      return callMethod(
        PoapNFTSerieV2,
        this,
        "getTokenUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getCollectionIndex: async (
      params?: PoapNFTSerieV2Types.CallMethodParams<"getCollectionIndex">
    ): Promise<PoapNFTSerieV2Types.CallMethodResult<"getCollectionIndex">> => {
      return callMethod(
        PoapNFTSerieV2,
        this,
        "getCollectionIndex",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNFTIndex: async (
      params?: PoapNFTSerieV2Types.CallMethodParams<"getNFTIndex">
    ): Promise<PoapNFTSerieV2Types.CallMethodResult<"getNFTIndex">> => {
      return callMethod(
        PoapNFTSerieV2,
        this,
        "getNFTIndex",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: PoapNFTSerieV2Types.CallMethodParams<"getName">
    ): Promise<PoapNFTSerieV2Types.CallMethodResult<"getName">> => {
      return callMethod(
        PoapNFTSerieV2,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDescription: async (
      params?: PoapNFTSerieV2Types.CallMethodParams<"getDescription">
    ): Promise<PoapNFTSerieV2Types.CallMethodResult<"getDescription">> => {
      return callMethod(
        PoapNFTSerieV2,
        this,
        "getDescription",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getImage: async (
      params?: PoapNFTSerieV2Types.CallMethodParams<"getImage">
    ): Promise<PoapNFTSerieV2Types.CallMethodResult<"getImage">> => {
      return callMethod(
        PoapNFTSerieV2,
        this,
        "getImage",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTraits: async (
      params?: PoapNFTSerieV2Types.CallMethodParams<"getTraits">
    ): Promise<PoapNFTSerieV2Types.CallMethodResult<"getTraits">> => {
      return callMethod(
        PoapNFTSerieV2,
        this,
        "getTraits",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTraitCount: async (
      params?: PoapNFTSerieV2Types.CallMethodParams<"getTraitCount">
    ): Promise<PoapNFTSerieV2Types.CallMethodResult<"getTraitCount">> => {
      return callMethod(
        PoapNFTSerieV2,
        this,
        "getTraitCount",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTraitAtIndex: async (
      params: PoapNFTSerieV2Types.CallMethodParams<"getTraitAtIndex">
    ): Promise<PoapNFTSerieV2Types.CallMethodResult<"getTraitAtIndex">> => {
      return callMethod(
        PoapNFTSerieV2,
        this,
        "getTraitAtIndex",
        params,
        getContractByCodeHash
      );
    },
    getHasParticipated: async (
      params?: PoapNFTSerieV2Types.CallMethodParams<"getHasParticipated">
    ): Promise<PoapNFTSerieV2Types.CallMethodResult<"getHasParticipated">> => {
      return callMethod(
        PoapNFTSerieV2,
        this,
        "getHasParticipated",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getMinter: async (
      params?: PoapNFTSerieV2Types.CallMethodParams<"getMinter">
    ): Promise<PoapNFTSerieV2Types.CallMethodResult<"getMinter">> => {
      return callMethod(
        PoapNFTSerieV2,
        this,
        "getMinter",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    burn: async (
      params?: PoapNFTSerieV2Types.CallMethodParams<"burn">
    ): Promise<PoapNFTSerieV2Types.CallMethodResult<"burn">> => {
      return callMethod(
        PoapNFTSerieV2,
        this,
        "burn",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    setParticipated: async (
      params?: PoapNFTSerieV2Types.CallMethodParams<"setParticipated">
    ): Promise<PoapNFTSerieV2Types.CallMethodResult<"setParticipated">> => {
      return callMethod(
        PoapNFTSerieV2,
        this,
        "setParticipated",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    lock: async (
      params: PoapNFTSerieV2Types.CallMethodParams<"lock">
    ): Promise<PoapNFTSerieV2Types.CallMethodResult<"lock">> => {
      return callMethod(
        PoapNFTSerieV2,
        this,
        "lock",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getTokenUri: async (
      params: PoapNFTSerieV2Types.SignExecuteMethodParams<"getTokenUri">
    ): Promise<PoapNFTSerieV2Types.SignExecuteMethodResult<"getTokenUri">> => {
      return signExecuteMethod(PoapNFTSerieV2, this, "getTokenUri", params);
    },
    getCollectionIndex: async (
      params: PoapNFTSerieV2Types.SignExecuteMethodParams<"getCollectionIndex">
    ): Promise<
      PoapNFTSerieV2Types.SignExecuteMethodResult<"getCollectionIndex">
    > => {
      return signExecuteMethod(
        PoapNFTSerieV2,
        this,
        "getCollectionIndex",
        params
      );
    },
    getNFTIndex: async (
      params: PoapNFTSerieV2Types.SignExecuteMethodParams<"getNFTIndex">
    ): Promise<PoapNFTSerieV2Types.SignExecuteMethodResult<"getNFTIndex">> => {
      return signExecuteMethod(PoapNFTSerieV2, this, "getNFTIndex", params);
    },
    getName: async (
      params: PoapNFTSerieV2Types.SignExecuteMethodParams<"getName">
    ): Promise<PoapNFTSerieV2Types.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(PoapNFTSerieV2, this, "getName", params);
    },
    getDescription: async (
      params: PoapNFTSerieV2Types.SignExecuteMethodParams<"getDescription">
    ): Promise<
      PoapNFTSerieV2Types.SignExecuteMethodResult<"getDescription">
    > => {
      return signExecuteMethod(PoapNFTSerieV2, this, "getDescription", params);
    },
    getImage: async (
      params: PoapNFTSerieV2Types.SignExecuteMethodParams<"getImage">
    ): Promise<PoapNFTSerieV2Types.SignExecuteMethodResult<"getImage">> => {
      return signExecuteMethod(PoapNFTSerieV2, this, "getImage", params);
    },
    getTraits: async (
      params: PoapNFTSerieV2Types.SignExecuteMethodParams<"getTraits">
    ): Promise<PoapNFTSerieV2Types.SignExecuteMethodResult<"getTraits">> => {
      return signExecuteMethod(PoapNFTSerieV2, this, "getTraits", params);
    },
    getTraitCount: async (
      params: PoapNFTSerieV2Types.SignExecuteMethodParams<"getTraitCount">
    ): Promise<
      PoapNFTSerieV2Types.SignExecuteMethodResult<"getTraitCount">
    > => {
      return signExecuteMethod(PoapNFTSerieV2, this, "getTraitCount", params);
    },
    getTraitAtIndex: async (
      params: PoapNFTSerieV2Types.SignExecuteMethodParams<"getTraitAtIndex">
    ): Promise<
      PoapNFTSerieV2Types.SignExecuteMethodResult<"getTraitAtIndex">
    > => {
      return signExecuteMethod(PoapNFTSerieV2, this, "getTraitAtIndex", params);
    },
    getHasParticipated: async (
      params: PoapNFTSerieV2Types.SignExecuteMethodParams<"getHasParticipated">
    ): Promise<
      PoapNFTSerieV2Types.SignExecuteMethodResult<"getHasParticipated">
    > => {
      return signExecuteMethod(
        PoapNFTSerieV2,
        this,
        "getHasParticipated",
        params
      );
    },
    getMinter: async (
      params: PoapNFTSerieV2Types.SignExecuteMethodParams<"getMinter">
    ): Promise<PoapNFTSerieV2Types.SignExecuteMethodResult<"getMinter">> => {
      return signExecuteMethod(PoapNFTSerieV2, this, "getMinter", params);
    },
    burn: async (
      params: PoapNFTSerieV2Types.SignExecuteMethodParams<"burn">
    ): Promise<PoapNFTSerieV2Types.SignExecuteMethodResult<"burn">> => {
      return signExecuteMethod(PoapNFTSerieV2, this, "burn", params);
    },
    setParticipated: async (
      params: PoapNFTSerieV2Types.SignExecuteMethodParams<"setParticipated">
    ): Promise<
      PoapNFTSerieV2Types.SignExecuteMethodResult<"setParticipated">
    > => {
      return signExecuteMethod(PoapNFTSerieV2, this, "setParticipated", params);
    },
    lock: async (
      params: PoapNFTSerieV2Types.SignExecuteMethodParams<"lock">
    ): Promise<PoapNFTSerieV2Types.SignExecuteMethodResult<"lock">> => {
      return signExecuteMethod(PoapNFTSerieV2, this, "lock", params);
    },
  };

  async multicall<Calls extends PoapNFTSerieV2Types.MultiCallParams>(
    calls: Calls
  ): Promise<PoapNFTSerieV2Types.MultiCallResults<Calls>>;
  async multicall<Callss extends PoapNFTSerieV2Types.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<PoapNFTSerieV2Types.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | PoapNFTSerieV2Types.MultiCallParams
      | PoapNFTSerieV2Types.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      PoapNFTSerieV2,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
