/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as PoapCollectionV2ContractJson } from "../V2/PoapCollectionV2.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Trait, AllStructs } from "./types";

// Custom types for the contract
export namespace PoapCollectionV2Types {
  export type Fields = {
    nftTemplateId: HexString;
    maxSupply: bigint;
    mintStartAt: bigint;
    mintEndAt: bigint;
    oneMintPerAddress: boolean;
    poapPrice: bigint;
    tokenIdPoap: HexString;
    isOpenPrice: boolean;
    tokenIdAirdrop: HexString;
    amountAirdropPerUser: bigint;
    airdropWhenHasParticipated: boolean;
    hashedPassword: HexString;
    lockPresenceUntil: bigint;
    eventImage: HexString;
    eventName: HexString;
    description: HexString;
    organizer: Address;
    location: HexString;
    eventStartAt: bigint;
    eventEndAt: bigint;
    isPublic: boolean;
    isBurnable: boolean;
    amountForStorageFees: bigint;
    amountForChainFees: bigint;
    amountPoapFees: bigint;
    totalSupply: bigint;
    amountAirdrop: bigint;
  };

  export type State = ContractState<Fields>;

  export type PoapMintedEvent = ContractEvent<{
    contractId: HexString;
    nftIndex: bigint;
    caller: Address;
    timestamp: bigint;
  }>;
  export type PoapParticipatedEvent = ContractEvent<{
    organizerAddress: Address;
    nftIndex: bigint;
    presenceAddressValidate: Address;
  }>;

  export interface CallMethodTable {
    getCollectionUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    totalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    nftByIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    validateNFT: {
      params: CallContractParams<{ nftId: HexString; nftIndex: bigint }>;
      result: CallContractResult<null>;
    };
    convert: {
      params: CallContractParams<{ array: HexString }>;
      result: CallContractResult<HexString>;
    };
    mint: {
      params: CallContractParams<{ amount: bigint; password: HexString }>;
      result: CallContractResult<HexString>;
    };
    setParticipatedPresence: {
      params: CallContractParams<{
        nftIndex: bigint;
        presenceAddressValidate: Address;
      }>;
      result: CallContractResult<null>;
    };
    sendAirdrop: {
      params: CallContractParams<{ addressToAirdrop: Address }>;
      result: CallContractResult<null>;
    };
    nftByAddress: {
      params: CallContractParams<{ caller: Address }>;
      result: CallContractResult<HexString>;
    };
    validateNFTAddress: {
      params: CallContractParams<{ nftId: HexString; address: Address }>;
      result: CallContractResult<null>;
    };
    getIsPublic: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<boolean>;
    };
    getAmountForStorageFees: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getAirdropWhenHasParticipated: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<boolean>;
    };
    getAmountPoapFees: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    claimFunds: {
      params: CallContractParams<{ amountToClaim: bigint }>;
      result: CallContractResult<null>;
    };
    withdrawStorageFees: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    withdrawChainFees: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    depositStorageFees: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    depositChainFees: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    withdrawAirdrop: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    getPoapPrice: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[bigint, HexString, boolean]>;
    };
    getOrganizer: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getCollectionUri: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    totalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    nftByIndex: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    validateNFT: {
      params: SignExecuteContractMethodParams<{
        nftId: HexString;
        nftIndex: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    convert: {
      params: SignExecuteContractMethodParams<{ array: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    mint: {
      params: SignExecuteContractMethodParams<{
        amount: bigint;
        password: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    setParticipatedPresence: {
      params: SignExecuteContractMethodParams<{
        nftIndex: bigint;
        presenceAddressValidate: Address;
      }>;
      result: SignExecuteScriptTxResult;
    };
    sendAirdrop: {
      params: SignExecuteContractMethodParams<{ addressToAirdrop: Address }>;
      result: SignExecuteScriptTxResult;
    };
    nftByAddress: {
      params: SignExecuteContractMethodParams<{ caller: Address }>;
      result: SignExecuteScriptTxResult;
    };
    validateNFTAddress: {
      params: SignExecuteContractMethodParams<{
        nftId: HexString;
        address: Address;
      }>;
      result: SignExecuteScriptTxResult;
    };
    getIsPublic: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getAmountForStorageFees: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getAirdropWhenHasParticipated: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getAmountPoapFees: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    claimFunds: {
      params: SignExecuteContractMethodParams<{ amountToClaim: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    withdrawStorageFees: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    withdrawChainFees: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    depositStorageFees: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    depositChainFees: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    withdrawAirdrop: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getPoapPrice: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getOrganizer: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  PoapCollectionV2Instance,
  PoapCollectionV2Types.Fields
> {
  encodeFields(fields: PoapCollectionV2Types.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  eventIndex = { PoapMinted: 0, PoapParticipated: 1 };

  at(address: string): PoapCollectionV2Instance {
    return new PoapCollectionV2Instance(address);
  }

  tests = {
    getCollectionUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapCollectionV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getCollectionUri",
        params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapCollectionV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "totalSupply", params, getContractByCodeHash);
    },
    nftByIndex: async (
      params: TestContractParamsWithoutMaps<
        PoapCollectionV2Types.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "nftByIndex", params, getContractByCodeHash);
    },
    validateNFT: async (
      params: TestContractParamsWithoutMaps<
        PoapCollectionV2Types.Fields,
        { nftId: HexString; nftIndex: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "validateNFT", params, getContractByCodeHash);
    },
    convert: async (
      params: TestContractParamsWithoutMaps<
        PoapCollectionV2Types.Fields,
        { array: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "convert", params, getContractByCodeHash);
    },
    mint: async (
      params: TestContractParamsWithoutMaps<
        PoapCollectionV2Types.Fields,
        { amount: bigint; password: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "mint", params, getContractByCodeHash);
    },
    setParticipatedPresence: async (
      params: TestContractParamsWithoutMaps<
        PoapCollectionV2Types.Fields,
        { nftIndex: bigint; presenceAddressValidate: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "setParticipatedPresence",
        params,
        getContractByCodeHash
      );
    },
    sendAirdrop: async (
      params: TestContractParamsWithoutMaps<
        PoapCollectionV2Types.Fields,
        { addressToAirdrop: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "sendAirdrop", params, getContractByCodeHash);
    },
    nftByAddress: async (
      params: TestContractParamsWithoutMaps<
        PoapCollectionV2Types.Fields,
        { caller: Address }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "nftByAddress", params, getContractByCodeHash);
    },
    validateNFTAddress: async (
      params: TestContractParamsWithoutMaps<
        PoapCollectionV2Types.Fields,
        { nftId: HexString; address: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "validateNFTAddress",
        params,
        getContractByCodeHash
      );
    },
    getIsPublic: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapCollectionV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "getIsPublic", params, getContractByCodeHash);
    },
    getAmountForStorageFees: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapCollectionV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "getAmountForStorageFees",
        params,
        getContractByCodeHash
      );
    },
    getAirdropWhenHasParticipated: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapCollectionV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(
        this,
        "getAirdropWhenHasParticipated",
        params,
        getContractByCodeHash
      );
    },
    getAmountPoapFees: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapCollectionV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "getAmountPoapFees",
        params,
        getContractByCodeHash
      );
    },
    claimFunds: async (
      params: TestContractParamsWithoutMaps<
        PoapCollectionV2Types.Fields,
        { amountToClaim: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "claimFunds", params, getContractByCodeHash);
    },
    withdrawStorageFees: async (
      params: TestContractParamsWithoutMaps<
        PoapCollectionV2Types.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "withdrawStorageFees",
        params,
        getContractByCodeHash
      );
    },
    withdrawChainFees: async (
      params: TestContractParamsWithoutMaps<
        PoapCollectionV2Types.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "withdrawChainFees",
        params,
        getContractByCodeHash
      );
    },
    depositStorageFees: async (
      params: TestContractParamsWithoutMaps<
        PoapCollectionV2Types.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "depositStorageFees",
        params,
        getContractByCodeHash
      );
    },
    depositChainFees: async (
      params: TestContractParamsWithoutMaps<
        PoapCollectionV2Types.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "depositChainFees",
        params,
        getContractByCodeHash
      );
    },
    withdrawAirdrop: async (
      params: TestContractParamsWithoutMaps<
        PoapCollectionV2Types.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdrawAirdrop", params, getContractByCodeHash);
    },
    getPoapPrice: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapCollectionV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<[bigint, HexString, boolean]>> => {
      return testMethod(this, "getPoapPrice", params, getContractByCodeHash);
    },
    getOrganizer: async (
      params: Omit<
        TestContractParamsWithoutMaps<PoapCollectionV2Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "getOrganizer", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: PoapCollectionV2Types.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const PoapCollectionV2 = new Factory(
  Contract.fromJson(
    PoapCollectionV2ContractJson,
    "",
    "6ab23409a3fc421004b40f29d06d92f8984a72c0bc08af7c8ce81e3a87ca213b",
    AllStructs
  )
);
registerContract(PoapCollectionV2);

// Use this class to interact with the blockchain
export class PoapCollectionV2Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<PoapCollectionV2Types.State> {
    return fetchContractState(PoapCollectionV2, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribePoapMintedEvent(
    options: EventSubscribeOptions<PoapCollectionV2Types.PoapMintedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      PoapCollectionV2.contract,
      this,
      options,
      "PoapMinted",
      fromCount
    );
  }

  subscribePoapParticipatedEvent(
    options: EventSubscribeOptions<PoapCollectionV2Types.PoapParticipatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      PoapCollectionV2.contract,
      this,
      options,
      "PoapParticipated",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | PoapCollectionV2Types.PoapMintedEvent
      | PoapCollectionV2Types.PoapParticipatedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      PoapCollectionV2.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    getCollectionUri: async (
      params?: PoapCollectionV2Types.CallMethodParams<"getCollectionUri">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"getCollectionUri">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "getCollectionUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params?: PoapCollectionV2Types.CallMethodParams<"totalSupply">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"totalSupply">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "totalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    nftByIndex: async (
      params: PoapCollectionV2Types.CallMethodParams<"nftByIndex">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"nftByIndex">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "nftByIndex",
        params,
        getContractByCodeHash
      );
    },
    validateNFT: async (
      params: PoapCollectionV2Types.CallMethodParams<"validateNFT">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"validateNFT">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "validateNFT",
        params,
        getContractByCodeHash
      );
    },
    convert: async (
      params: PoapCollectionV2Types.CallMethodParams<"convert">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"convert">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "convert",
        params,
        getContractByCodeHash
      );
    },
    mint: async (
      params: PoapCollectionV2Types.CallMethodParams<"mint">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"mint">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "mint",
        params,
        getContractByCodeHash
      );
    },
    setParticipatedPresence: async (
      params: PoapCollectionV2Types.CallMethodParams<"setParticipatedPresence">
    ): Promise<
      PoapCollectionV2Types.CallMethodResult<"setParticipatedPresence">
    > => {
      return callMethod(
        PoapCollectionV2,
        this,
        "setParticipatedPresence",
        params,
        getContractByCodeHash
      );
    },
    sendAirdrop: async (
      params: PoapCollectionV2Types.CallMethodParams<"sendAirdrop">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"sendAirdrop">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "sendAirdrop",
        params,
        getContractByCodeHash
      );
    },
    nftByAddress: async (
      params: PoapCollectionV2Types.CallMethodParams<"nftByAddress">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"nftByAddress">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "nftByAddress",
        params,
        getContractByCodeHash
      );
    },
    validateNFTAddress: async (
      params: PoapCollectionV2Types.CallMethodParams<"validateNFTAddress">
    ): Promise<
      PoapCollectionV2Types.CallMethodResult<"validateNFTAddress">
    > => {
      return callMethod(
        PoapCollectionV2,
        this,
        "validateNFTAddress",
        params,
        getContractByCodeHash
      );
    },
    getIsPublic: async (
      params?: PoapCollectionV2Types.CallMethodParams<"getIsPublic">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"getIsPublic">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "getIsPublic",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getAmountForStorageFees: async (
      params?: PoapCollectionV2Types.CallMethodParams<"getAmountForStorageFees">
    ): Promise<
      PoapCollectionV2Types.CallMethodResult<"getAmountForStorageFees">
    > => {
      return callMethod(
        PoapCollectionV2,
        this,
        "getAmountForStorageFees",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getAirdropWhenHasParticipated: async (
      params?: PoapCollectionV2Types.CallMethodParams<"getAirdropWhenHasParticipated">
    ): Promise<
      PoapCollectionV2Types.CallMethodResult<"getAirdropWhenHasParticipated">
    > => {
      return callMethod(
        PoapCollectionV2,
        this,
        "getAirdropWhenHasParticipated",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getAmountPoapFees: async (
      params?: PoapCollectionV2Types.CallMethodParams<"getAmountPoapFees">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"getAmountPoapFees">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "getAmountPoapFees",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    claimFunds: async (
      params: PoapCollectionV2Types.CallMethodParams<"claimFunds">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"claimFunds">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "claimFunds",
        params,
        getContractByCodeHash
      );
    },
    withdrawStorageFees: async (
      params: PoapCollectionV2Types.CallMethodParams<"withdrawStorageFees">
    ): Promise<
      PoapCollectionV2Types.CallMethodResult<"withdrawStorageFees">
    > => {
      return callMethod(
        PoapCollectionV2,
        this,
        "withdrawStorageFees",
        params,
        getContractByCodeHash
      );
    },
    withdrawChainFees: async (
      params: PoapCollectionV2Types.CallMethodParams<"withdrawChainFees">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"withdrawChainFees">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "withdrawChainFees",
        params,
        getContractByCodeHash
      );
    },
    depositStorageFees: async (
      params: PoapCollectionV2Types.CallMethodParams<"depositStorageFees">
    ): Promise<
      PoapCollectionV2Types.CallMethodResult<"depositStorageFees">
    > => {
      return callMethod(
        PoapCollectionV2,
        this,
        "depositStorageFees",
        params,
        getContractByCodeHash
      );
    },
    depositChainFees: async (
      params: PoapCollectionV2Types.CallMethodParams<"depositChainFees">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"depositChainFees">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "depositChainFees",
        params,
        getContractByCodeHash
      );
    },
    withdrawAirdrop: async (
      params: PoapCollectionV2Types.CallMethodParams<"withdrawAirdrop">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"withdrawAirdrop">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "withdrawAirdrop",
        params,
        getContractByCodeHash
      );
    },
    getPoapPrice: async (
      params?: PoapCollectionV2Types.CallMethodParams<"getPoapPrice">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"getPoapPrice">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "getPoapPrice",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getOrganizer: async (
      params?: PoapCollectionV2Types.CallMethodParams<"getOrganizer">
    ): Promise<PoapCollectionV2Types.CallMethodResult<"getOrganizer">> => {
      return callMethod(
        PoapCollectionV2,
        this,
        "getOrganizer",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getCollectionUri: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"getCollectionUri">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"getCollectionUri">
    > => {
      return signExecuteMethod(
        PoapCollectionV2,
        this,
        "getCollectionUri",
        params
      );
    },
    totalSupply: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"totalSupply">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"totalSupply">
    > => {
      return signExecuteMethod(PoapCollectionV2, this, "totalSupply", params);
    },
    nftByIndex: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"nftByIndex">
    ): Promise<PoapCollectionV2Types.SignExecuteMethodResult<"nftByIndex">> => {
      return signExecuteMethod(PoapCollectionV2, this, "nftByIndex", params);
    },
    validateNFT: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"validateNFT">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"validateNFT">
    > => {
      return signExecuteMethod(PoapCollectionV2, this, "validateNFT", params);
    },
    convert: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"convert">
    ): Promise<PoapCollectionV2Types.SignExecuteMethodResult<"convert">> => {
      return signExecuteMethod(PoapCollectionV2, this, "convert", params);
    },
    mint: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"mint">
    ): Promise<PoapCollectionV2Types.SignExecuteMethodResult<"mint">> => {
      return signExecuteMethod(PoapCollectionV2, this, "mint", params);
    },
    setParticipatedPresence: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"setParticipatedPresence">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"setParticipatedPresence">
    > => {
      return signExecuteMethod(
        PoapCollectionV2,
        this,
        "setParticipatedPresence",
        params
      );
    },
    sendAirdrop: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"sendAirdrop">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"sendAirdrop">
    > => {
      return signExecuteMethod(PoapCollectionV2, this, "sendAirdrop", params);
    },
    nftByAddress: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"nftByAddress">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"nftByAddress">
    > => {
      return signExecuteMethod(PoapCollectionV2, this, "nftByAddress", params);
    },
    validateNFTAddress: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"validateNFTAddress">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"validateNFTAddress">
    > => {
      return signExecuteMethod(
        PoapCollectionV2,
        this,
        "validateNFTAddress",
        params
      );
    },
    getIsPublic: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"getIsPublic">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"getIsPublic">
    > => {
      return signExecuteMethod(PoapCollectionV2, this, "getIsPublic", params);
    },
    getAmountForStorageFees: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"getAmountForStorageFees">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"getAmountForStorageFees">
    > => {
      return signExecuteMethod(
        PoapCollectionV2,
        this,
        "getAmountForStorageFees",
        params
      );
    },
    getAirdropWhenHasParticipated: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"getAirdropWhenHasParticipated">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"getAirdropWhenHasParticipated">
    > => {
      return signExecuteMethod(
        PoapCollectionV2,
        this,
        "getAirdropWhenHasParticipated",
        params
      );
    },
    getAmountPoapFees: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"getAmountPoapFees">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"getAmountPoapFees">
    > => {
      return signExecuteMethod(
        PoapCollectionV2,
        this,
        "getAmountPoapFees",
        params
      );
    },
    claimFunds: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"claimFunds">
    ): Promise<PoapCollectionV2Types.SignExecuteMethodResult<"claimFunds">> => {
      return signExecuteMethod(PoapCollectionV2, this, "claimFunds", params);
    },
    withdrawStorageFees: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"withdrawStorageFees">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"withdrawStorageFees">
    > => {
      return signExecuteMethod(
        PoapCollectionV2,
        this,
        "withdrawStorageFees",
        params
      );
    },
    withdrawChainFees: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"withdrawChainFees">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"withdrawChainFees">
    > => {
      return signExecuteMethod(
        PoapCollectionV2,
        this,
        "withdrawChainFees",
        params
      );
    },
    depositStorageFees: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"depositStorageFees">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"depositStorageFees">
    > => {
      return signExecuteMethod(
        PoapCollectionV2,
        this,
        "depositStorageFees",
        params
      );
    },
    depositChainFees: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"depositChainFees">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"depositChainFees">
    > => {
      return signExecuteMethod(
        PoapCollectionV2,
        this,
        "depositChainFees",
        params
      );
    },
    withdrawAirdrop: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"withdrawAirdrop">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"withdrawAirdrop">
    > => {
      return signExecuteMethod(
        PoapCollectionV2,
        this,
        "withdrawAirdrop",
        params
      );
    },
    getPoapPrice: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"getPoapPrice">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"getPoapPrice">
    > => {
      return signExecuteMethod(PoapCollectionV2, this, "getPoapPrice", params);
    },
    getOrganizer: async (
      params: PoapCollectionV2Types.SignExecuteMethodParams<"getOrganizer">
    ): Promise<
      PoapCollectionV2Types.SignExecuteMethodResult<"getOrganizer">
    > => {
      return signExecuteMethod(PoapCollectionV2, this, "getOrganizer", params);
    },
  };

  async multicall<Calls extends PoapCollectionV2Types.MultiCallParams>(
    calls: Calls
  ): Promise<PoapCollectionV2Types.MultiCallResults<Calls>>;
  async multicall<Callss extends PoapCollectionV2Types.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<PoapCollectionV2Types.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | PoapCollectionV2Types.MultiCallParams
      | PoapCollectionV2Types.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      PoapCollectionV2,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
